name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run-script build
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Grant access
        run: ssh ubuntu@ec2-18-222-208-138.us-east-2.compute.amazonaws.com sudo chmod 777 /var/www/coderunner
      - name: Upload new version
        run: rsync -crlOt ./build/ ubuntu@ec2-18-222-208-138.us-east-2.compute.amazonaws.com:/var/www/coderunner
      - name: Restore permissions
        run: ssh ubuntu@ec2-18-222-208-138.us-east-2.compute.amazonaws.com sudo chmod -R 755 /var/www/coderunner
